name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      experiment_name:
        description: 'Name of the Azure ML experiment'
        required: true
      job_config:
        description: 'Path to the job YAML configuration file'
        required: true
        default: 'src/job.yml'
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}


