name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      experiment_name:
        description: 'Name of the Azure ML experiment'
        required: true
      job_config:
        description: 'Path to the job YAML configuration file'
        required: true
        default: 'src/jobwithcluster.yml'
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Trigger Azure ML Job
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        AZURE_ML_WORKSPACE: ${{ secrets.AZURE_ML_WORKSPACE }}
      run: |
        python <<EOF
        from azure.ai.ml import MLClient
        from azure.identity import DefaultAzureCredential
        from azure.ai.ml.entities import Job

        # Authenticate with Azure ML
        credential = DefaultAzureCredential()
        ml_client = MLClient(
            credential=credential,
            subscription_id='${{ secrets.AZURE_SUBSCRIPTION_ID }}',
            resource_group_name='${{ secrets.AZURE_RESOURCE_GROUP }}',
            workspace_name='${{ secrets.AZURE_ML_WORKSPACE }}'
        )

        # Load job configuration
        import yaml
        with open('${{ github.event.inputs.job_config }}', 'r') as f:
            job_config = yaml.safe_load(f)

        # Create and submit job
        job = Job(**job_config)
        ml_client.jobs.create_or_update(job)
        print(f"Job {job.name} submitted to Azure ML workspace.")
        EOF

