name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      experiment_name:
        description: 'Name of the Azure ML experiment'
        required: true
      job_config:
        description: 'Path to the job YAML configuration file'
        required: true
        default: 'src/job.yml'
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Azure ML SDK
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml azure-identity
        pip install --upgrade azure-ai-ml

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Trigger Azure ML Job
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        AZURE_ML_WORKSPACE: ${{ secrets.AZURE_ML_WORKSPACE }}
      run: |
        az ml job create --file ${{ github.event.inputs.job_config }} --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
      
